export const MOBILE_LAYOUT_BREAKPOINT_PX = 900;
export const MOBILE_LAYOUT_MAX_WIDTH_PX = MOBILE_LAYOUT_BREAKPOINT_PX - 1;
export const MOBILE_LAYOUT_MEDIA_QUERY = `(max-width: ${MOBILE_LAYOUT_MAX_WIDTH_PX}px)`;
