use super::*;

pub(in crate::services::discord::turn_bridge) struct CompletionPostludeContext {
    pub(in crate::services::discord::turn_bridge) shared_owned: Arc<SharedData>,
    pub(in crate::services::discord::turn_bridge) gateway: Arc<dyn TurnGateway>,
    pub(in crate::services::discord::turn_bridge) channel_id: ChannelId,
    pub(in crate::services::discord::turn_bridge) provider: ProviderKind,
    pub(in crate::services::discord::turn_bridge) cancel_token:
        Arc<crate::services::provider::CancelToken>,
    pub(in crate::services::discord::turn_bridge) user_msg_id: Option<MessageId>,
    pub(in crate::services::discord::turn_bridge) turn_id: String,
    pub(in crate::services::discord::turn_bridge) request_owner_name: String,
    pub(in crate::services::discord::turn_bridge) final_session_status: &'static str,
    pub(in crate::services::discord::turn_bridge) status_panel_started_at: i64,
    pub(in crate::services::discord::turn_bridge) has_queued_turns: bool,
    pub(in crate::services::discord::turn_bridge) defer_watcher_resume: bool,
    pub(in crate::services::discord::turn_bridge) can_chain_locally: bool,
    pub(in crate::services::discord::turn_bridge) single_message_panel_footer_mode: bool,
    pub(in crate::services::discord::turn_bridge) is_external_input_tui_direct: bool,
    pub(in crate::services::discord::turn_bridge) context_window_tokens: u64,
    pub(in crate::services::discord::turn_bridge) context_compact_percent: u64,
    pub(in crate::services::discord::turn_bridge) turn_start: std::time::Instant,
}

pub(in crate::services::discord::turn_bridge) struct CompletionPostludeState {
    pub(in crate::services::discord::turn_bridge) full_response: String,
    pub(in crate::services::discord::turn_bridge) user_text_owned: String,
    pub(in crate::services::discord::turn_bridge) role_binding: Option<RoleBinding>,
    pub(in crate::services::discord::turn_bridge) adk_session_key: Option<String>,
    pub(in crate::services::discord::turn_bridge) adk_session_name: Option<String>,
    pub(in crate::services::discord::turn_bridge) adk_session_info: Option<String>,
    pub(in crate::services::discord::turn_bridge) adk_cwd: Option<String>,
    pub(in crate::services::discord::turn_bridge) dispatch_id: Option<String>,
    pub(in crate::services::discord::turn_bridge) dispatch_kind: Option<String>,
    pub(in crate::services::discord::turn_bridge) new_session_id: Option<String>,
    pub(in crate::services::discord::turn_bridge) new_raw_provider_session_id: Option<String>,
    pub(in crate::services::discord::turn_bridge) status_panel_terminal_committed: bool,
    pub(in crate::services::discord::turn_bridge) bridge_should_emit_completion: bool,
    pub(in crate::services::discord::turn_bridge) current_msg_id: MessageId,
    pub(in crate::services::discord::turn_bridge) status_panel_msg_id: Option<MessageId>,
    pub(in crate::services::discord::turn_bridge) last_status_panel_text: String,
    pub(in crate::services::discord::turn_bridge) completion_footer_terminal_text: Option<String>,
    pub(in crate::services::discord::turn_bridge) busy_requeue_outcome:
        Option<super::super::followup_requeue::FollowupRequeueOutcome>,
    pub(in crate::services::discord::turn_bridge) spin_idx: usize,
    pub(in crate::services::discord::turn_bridge) status_panel_generation: u64,
    pub(in crate::services::discord::turn_bridge) preserve_inflight_for_cleanup_retry: bool,
    pub(in crate::services::discord::turn_bridge) tmux_last_offset: Option<u64>,
    pub(in crate::services::discord::turn_bridge) watcher_owner_channel_id: ChannelId,
    pub(in crate::services::discord::turn_bridge) bridge_relay_delegated_to_watcher: bool,
    pub(in crate::services::discord::turn_bridge) is_prompt_too_long: bool,
    pub(in crate::services::discord::turn_bridge) resume_failure_detected: bool,
    pub(in crate::services::discord::turn_bridge) recovery_retry: bool,
    pub(in crate::services::discord::turn_bridge) rx_disconnected: bool,
    pub(in crate::services::discord::turn_bridge) tmux_handed_off: bool,
    pub(in crate::services::discord::turn_bridge) bridge_output_owner: Option<BridgeOutputOwner>,
    pub(in crate::services::discord::turn_bridge) terminal_delivery_committed: bool,
    pub(in crate::services::discord::turn_bridge) terminal_session_reset_required: bool,
    pub(in crate::services::discord::turn_bridge) transcript_events: Vec<SessionTranscriptEvent>,
    pub(in crate::services::discord::turn_bridge) accumulated_input_tokens: u64,
    pub(in crate::services::discord::turn_bridge) accumulated_cache_create_tokens: u64,
    pub(in crate::services::discord::turn_bridge) accumulated_cache_read_tokens: u64,
    pub(in crate::services::discord::turn_bridge) accumulated_output_tokens: u64,
    pub(in crate::services::discord::turn_bridge) accumulated_memory_input_tokens: u64,
    pub(in crate::services::discord::turn_bridge) accumulated_memory_output_tokens: u64,
    pub(in crate::services::discord::turn_bridge) transport_error: bool,
    pub(in crate::services::discord::turn_bridge) api_friction_reports:
        Vec<crate::services::api_friction::ApiFrictionReport>,
    pub(in crate::services::discord::turn_bridge) cancelled: bool,
    pub(in crate::services::discord::turn_bridge) restart_followup_pending: bool,
    pub(in crate::services::discord::turn_bridge) bridge_skip_holder_owns_inflight: bool,
    pub(in crate::services::discord::turn_bridge) completion_guard: CompletionGuard,
    pub(in crate::services::discord::turn_bridge) inflight_guard: InflightCleanupGuard,
    pub(in crate::services::discord::turn_bridge) inflight_state: InflightTurnState,
}
