use super::super::{EndpointDoc, body_param, ep, header_param, path_param, query_param};
use serde_json::json;

pub(super) fn endpoints() -> Vec<EndpointDoc> {
    vec![
        ep("GET","/api/kakao/calendar/accounts","kakao-calendar","List explicitly allowed calendar accounts and last check time; configured is not verified consent. Operator Bearer token required."),
        ep("POST","/api/kakao/calendar/accounts/{accountId}/check","kakao-calendar","Verify token identity and talk_calendar consent; changed or duplicate identity is rejected.")
            .with_params([("accountId",path_param("Configured account alias, not a friend UUID"))]),
        ep("POST","/api/kakao/calendar/events","kakao-calendar","Durably accept one managed event for each consenting account. 202 means accepted, not remotely applied. Preserve the same Idempotency-Key through retries and agent fallback; use a new key only for a new user action.")
            .with_params([("Idempotency-Key",header_param("string",true,"Stable originating user-action key, 1 to 128 printable ASCII characters")),("accountIds",body_param("array",true,"One to sixteen distinct allowed aliases from the same Kakao app")),("title",body_param("string",true,"1 to 50 characters")),("time",body_param("object",true,"startAt/endAt RFC3339 with matching IANA timeZone; timed nonrecurring events only")),("description",body_param("string",false,"At most 5000 characters")),("location",body_param("object",false,"name, at most 100 characters")),("reminders",body_param("array",false,"One or two supported minute offsets; empty does not disable reminders"))])
            .with_example(json!({"accountIds":["default","friend"],"title":"meeting","time":{"startAt":"2026-09-30T10:00:00+09:00","endAt":"2026-09-30T11:00:00+09:00","timeZone":"Asia/Seoul"}}),json!({"eventId":"internal-uuid","revision":1,"status":"accepted"})),
        ep("GET","/api/kakao/calendar/events","kakao-calendar","List AgentDesk-managed events only; account allowlist and operator authentication apply to every read.")
            .with_params([("limit",query_param("integer",false,"1 to 100; default 25")),("before",query_param("string",false,"Opaque UUID nextCursor from previous page"))]),
        ep("GET","/api/kakao/calendar/events/{eventId}","kakao-calendar","Read managed intent and per-account applied revisions/status; success requires all targets, unknown requires reconciliation.").with_params([("eventId",path_param("Internal managed-event UUID"))]),
        ep("PATCH","/api/kakao/calendar/events/{eventId}","kakao-calendar","Accept a conditional update. Omitted fields are kept; description null clears. Preserve action key when retrying; replay precedes revision check.").with_params([("eventId",path_param("Internal UUID")),("Idempotency-Key",header_param("string",true,"New stable key for this update action")),("expectedRevision",body_param("integer",true,"Last observed revision"))]),
        ep("DELETE","/api/kakao/calendar/events/{eventId}","kakao-calendar","Record a durable deletion intent. JSON body requires expectedRevision; completion is per target. Completed deletion scrubs calendar content while retaining dedupe evidence.").with_params([("eventId",path_param("Internal UUID")),("Idempotency-Key",header_param("string",true,"New stable key for this delete action")),("expectedRevision",body_param("integer",true,"Last observed revision"))]),
        ep("GET","/api/kakao/calendar/events/{eventId}/operations","kakao-calendar","Read up to 200 latest redacted operations, dispatch stages and recovery notes.").with_params([("eventId",path_param("Internal UUID"))]),
        ep("POST","/api/kakao/calendar/events/{eventId}/operations/{operationId}/recover","kakao-calendar","Operator-only audited recovery. Never retry unknown creates automatically. Stop/restart the previous credential owner before resolving ambiguity; consult docs/integrations/kakao-calendar.md.").with_params([("eventId",path_param("Internal UUID")),("operationId",path_param("Operation UUID")),("resolution",body_param("string",true,"retry, adopt or confirm_not_applied")),("note",body_param("string",true,"Non-secret audit evidence, 10 to 1000 bytes")),("credentialOwnerRestarted",body_param("boolean",true,"Operator attestation that old execution has stopped")),("remoteEventId",body_param("string",false,"Only for verified adoption; forbidden in ordinary CRUD"))]),
    ]
}
