#!/usr/bin/env python3
"""Create a portable AgentDesk operator starter scaffold."""

from __future__ import annotations

import argparse
import json
import os
import shlex
from dataclasses import dataclass
from pathlib import Path
from typing import Any


PRIVATE_MARKERS = (
    "/Users/" "itismyfield",
    "mac-mini-release",
    "DISCORD_BOT_TOKEN",
    "MEMENTO_ACCESS_KEY=",
)


@dataclass(frozen=True)
class FileSpec:
    path: Path
    content: str
    label: str


@dataclass(frozen=True)
class DirSpec:
    path: Path
    label: str


def env_path(name: str) -> Path | None:
    value = os.environ.get(name, "").strip()
    return Path(value).expanduser() if value else None


def default_root() -> Path:
    return env_path("AGENTDESK_ROOT_DIR") or Path.home() / ".adk" / "release"


def as_resolved_path(value: Path) -> Path:
    return value.expanduser().resolve()


def path_string(path: Path) -> str:
    return path.as_posix()


def yaml_string(value: str) -> str:
    return json.dumps(value)


def shell_export(name: str, value: Path | str) -> str:
    return f"export {name}={shlex.quote(str(value))}"


def commented_shell_export(name: str, value: Path | str) -> str:
    return f"# {shell_export(name, value)}"


def starter_config(root: Path) -> str:
    root_s = path_string(root)
    shared_prompt = path_string(root / "config" / "agents" / "_shared.prompt.md")
    agent_prompt = path_string(root / "config" / "agents" / "ch-td.prompt.md")
    workspace = path_string(root / "workspaces" / "ch-td")
    data_dir = path_string(root / "data")
    return f"""# Portable AgentDesk starter config generated by scripts/operator-init-portable.py.
# Replace Discord ids/tokens through onboarding before enabling Discord relay.
server:
  port: 8791
  host: "127.0.0.1"

shared_prompt: {yaml_string(shared_prompt)}

providers:
  claude:
    tui_hosting: true
  codex:
    tui_hosting: true
  gemini:
    tui_hosting: false
  qwen:
    tui_hosting: false
  opencode:
    tui_hosting: false

data:
  dir: {yaml_string(data_dir)}

policies:
  dir: "./policies"
  hot_reload: true

routines:
  enabled: false
  dir: "./routines"
  additional_dirs: []
  default_timezone: "Asia/Seoul"

agents:
  - id: ch-td
    name: "Technical Director"
    provider: claude
    channels:
      claude:
        name: "ch-td-cc"
        workspace: {yaml_string(workspace)}
        prompt_file: {yaml_string(agent_prompt)}
    keywords:
      - "architecture"
      - "code"
    department: engineering

github:
  repos: []

# Runtime root reference for operators reading this file:
# {root_s}
"""


def launchd_env_example(root: Path) -> str:
    obsidian_vault = root / "ObsidianVault"
    obsidian_remote = obsidian_vault / "RemoteVault"
    return "\n".join(
        [
            "# Copy this file to launchd.env, then edit operator-local paths as needed.",
            shell_export("AGENTDESK_ROOT_DIR", root),
            shell_export("AGENTDESK_OPERATOR_WORKDIR", root / "workspaces" / "ch-td"),
            shell_export(
                "AGENTDESK_MIGRATED_AGENTFACTORY_WORKDIR",
                root / "workspaces" / "agentfactory",
            ),
            shell_export(
                "AGENTDESK_MEMORY_MERGE_SKILL",
                root / "skills" / "memory-merge" / "SKILL.md",
            ),
            "",
            "# Optional Obsidian connector paths. Leave commented when not installed.",
            commented_shell_export("OBSIDIAN_VAULT_ROOT", obsidian_vault),
            commented_shell_export("OBSIDIAN_REMOTE_VAULT_ROOT", obsidian_remote),
            commented_shell_export(
                "AGENTDESK_OBSIDIAN_AGENTS_SRC",
                obsidian_remote / "adk-config" / "agents",
            ),
            commented_shell_export(
                "AGENTDESK_OBSIDIAN_SKILL_ROOT",
                obsidian_remote / "99_Skills",
            ),
            "",
        ]
    )


def shared_prompt() -> str:
    return """You are an AgentDesk operator agent.
Use the repository, runtime config, and current command output as the source of truth.
Do not assume operator-specific absolute paths.
"""


def agent_prompt() -> str:
    return """You are the technical director for this AgentDesk runtime.
Keep implementation work scoped, testable, and aligned with the local source of truth.
"""


def build_files(root: Path, config_path: Path) -> list[FileSpec]:
    return [
        FileSpec(config_path, starter_config(root), "agentdesk config"),
        FileSpec(
            root / "config" / "launchd.env.example",
            launchd_env_example(root),
            "launchd env example",
        ),
        FileSpec(
            root / "config" / "agents" / "_shared.prompt.md",
            shared_prompt(),
            "shared prompt",
        ),
        FileSpec(
            root / "config" / "agents" / "ch-td.prompt.md",
            agent_prompt(),
            "starter agent prompt",
        ),
    ]


def build_dirs(root: Path, with_obsidian_stubs: bool) -> list[DirSpec]:
    dirs = [
        DirSpec(root / "config" / "agents", "agent prompt directory"),
        DirSpec(root / "data", "data directory"),
        DirSpec(root / "logs", "launchd log directory"),
        DirSpec(root / "runtime", "runtime directory"),
        DirSpec(root / "workspaces" / "ch-td", "starter workspace"),
        DirSpec(root / "workspaces" / "agentfactory", "migrated launchd workspace"),
    ]
    if with_obsidian_stubs:
        obsidian_vault = root / "ObsidianVault"
        obsidian_remote = obsidian_vault / "RemoteVault"
        dirs.extend(
            [
                DirSpec(obsidian_vault, "obsidian vault stub"),
                DirSpec(
                    obsidian_remote / "adk-config" / "agents",
                    "obsidian agent prompt source stub",
                ),
                DirSpec(
                    obsidian_remote / "99_Skills",
                    "obsidian skill root stub",
                ),
            ]
        )
    return dirs


def validate_no_private_markers(files: list[FileSpec]) -> None:
    rendered = "\n".join(file.content for file in files)
    for marker in PRIVATE_MARKERS:
        if marker in rendered:
            raise SystemExit(f"refusing to write private starter marker: {marker}")


def apply_plan(
    files: list[FileSpec],
    dirs: list[DirSpec],
    *,
    dry_run: bool,
    force: bool,
) -> dict[str, Any]:
    created: list[str] = []
    skipped: list[str] = []
    would_create: list[str] = []
    would_skip: list[str] = []

    for directory in dirs:
        exists = directory.path.is_dir()
        target = path_string(directory.path)
        if dry_run:
            (would_skip if exists else would_create).append(target)
            continue
        if exists:
            skipped.append(target)
            continue
        directory.path.mkdir(parents=True, exist_ok=True)
        created.append(target)

    for file in files:
        exists = file.path.exists()
        target = path_string(file.path)
        if dry_run:
            (would_skip if exists and not force else would_create).append(target)
            continue
        if exists and not force:
            skipped.append(target)
            continue
        file.path.parent.mkdir(parents=True, exist_ok=True)
        file.path.write_text(file.content, encoding="utf-8")
        created.append(target)

    return {
        "dry_run": dry_run,
        "force": force,
        "created": created,
        "skipped": skipped,
        "would_create": would_create,
        "would_skip": would_skip,
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=default_root(),
        help="AgentDesk release root. Defaults to AGENTDESK_ROOT_DIR or ~/.adk/release.",
    )
    parser.add_argument(
        "--config",
        type=Path,
        help="Config path to write. Defaults to <root>/config/agentdesk.yaml.",
    )
    parser.add_argument(
        "--with-obsidian-stubs",
        action="store_true",
        help="Create optional local Obsidian connector stub directories under the root.",
    )
    parser.add_argument("--force", action="store_true", help="Overwrite existing starter files.")
    parser.add_argument("--dry-run", action="store_true", help="Print the plan without writing files.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root = as_resolved_path(args.root)
    config_path = as_resolved_path(args.config) if args.config else root / "config" / "agentdesk.yaml"
    files = build_files(root, config_path)
    dirs = build_dirs(root, args.with_obsidian_stubs)
    validate_no_private_markers(files)
    result = apply_plan(files, dirs, dry_run=args.dry_run, force=args.force)
    result.update(
        {
            "root": path_string(root),
            "config_path": path_string(config_path),
            "with_obsidian_stubs": bool(args.with_obsidian_stubs),
        }
    )
    print(json.dumps(result, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
