export {
  getSession,
  getOffices,
  createOffice,
  updateOffice,
  deleteOffice,
  addAgentToOffice,
  removeAgentFromOffice,
  updateOfficeAgent,
  batchAddAgentsToOffice,
  getCachedAgents,
  getAgents,
  getAgent,
  createAgent,
  updateAgent,
  deleteAgent,
  setupAgent,
  archiveAgent,
  unarchiveAgent,
  duplicateAgent,
  getAgentOffices,
  getAuditLogs,
  getDepartments,
  createDepartment,
  updateDepartment,
  deleteDepartment,
  getSettings,
  saveSettings,
  getVoiceConfig,
  saveVoiceConfig,
  getStats,
  getKanbanCards,
  createKanbanCard,
  updateKanbanCard,
  deleteKanbanCard,
  retryKanbanCard,
  redispatchKanbanCard,
  patchKanbanDeferDod,
  assignKanbanIssue,
  getKanbanRepoSources,
  addKanbanRepoSource,
  updateKanbanRepoSource,
  deleteKanbanRepoSource,
  getTaskDispatches,
  getDispatchDeliveryEvents,
  getDispatchedSessions,
  assignDispatchedSession,
  getAgentCron,
  getAgentDispatchedSessions,
  getAgentTurn,
  getAgentTranscripts,
  getAgentSkills,
  getAgentQuality,
  getAgentQualityRanking,
  getSkillRanking,
  getSkillTrend,
  getHealth,
  getCachedHealth,
  getPromptManifestRetention,
  getTokenAnalytics,
  getCachedTokenAnalytics,
  getDiscordBindings,
  getDiscordChannelInfo,
  getCronJobs,
  getMachineStatus,
  getActivityHeatmap,
  getStreaks,
  getAchievements,
  getGitHubIssues,
  closeGitHubIssue,
  getCachedGitHubRepos,
  getGitHubRepos,
  getMessages,
  sendMessage,
  getRoundTableMeetings,
  getRoundTableMeeting,
  deleteRoundTableMeeting,
  updateRoundTableMeetingIssueRepo,
  createRoundTableIssues,
  startRoundTableMeeting,
  getSkillCatalog,
  generateAutoQueue,
  activateAutoQueue,
  getAutoQueueStatus,
  getAutoQueueHistory,
  skipAutoQueueEntry,
  updateAutoQueueEntry,
  updateAutoQueueRun,
  getPipelineStages,
  getPipelineStagesForAgent,
  savePipelineStages,
  deletePipelineStages,
  getCardPipelineStatus,
  getCardTranscripts,
  getRuntimeConfig,
  saveRuntimeConfig,
  getEscalationSettings,
  saveEscalationSettings,
  reorderAutoQueueEntries,
  resetAutoQueue,
  getDefaultPipeline,
  getEffectivePipeline,
  getRepoPipeline,
  setRepoPipeline,
  getAgentPipeline,
  setAgentPipeline,
  createDispatch,
  getKanbanReviews,
  saveReviewDecisions,
  triggerDecidedRework,
  getStalledCards,
  bulkKanbanAction,
  getAgentTimeline,
  getCardAuditLog,
  getCardGitHubComments,
  onApiError,
  ApiRequestError,
  VoiceConfigApiError,
  // #2050 P3 finding 16 — surface helpers some components were importing
  // from "../api/client" directly. Re-exporting here lets the dashboard
  // converge on a single import path.
  getRoundTableMeetingChannels,
  discardRoundTableIssue,
  discardAllRoundTableIssues,
  resetGlobalAutoQueue,
  getHomeKpiTrends,
  getPhaseGateCatalog,
  requestGenerateAutoQueue,
} from "./client";

export type {
  AutoQueueThreadLink,
  AutoQueueRun,
  AutoQueueStatus,
  AutoQueueHistoryRun,
  PhaseGateKind,
  PhaseGateCatalog,
  RequestGenerateAutoQueueBody,
  RequestGenerateAutoQueueResponse,
  AutoQueueHistorySummary,
  AutoQueueHistoryResponse,
  DispatchQueueEntry,
  CronJob,
  CronSchedule,
  CronJobState,
  AgentTurnToolEvent,
  AgentTurnState,
  SessionTranscriptEventKind,
  SessionTranscriptEvent,
  SessionTranscript,
  AgentSkill,
  AgentSkillsResponse,
  AgentOfficeMembership,
  AgentQualityWindow,
  AgentQualityDailyRecord,
  AgentQualitySummary,
  AgentQualityRankingEntry,
  AgentQualityRankingResponse,
  AuditLogEntry,
  SkillRankingOverallRow,
  SkillRankingByAgentRow,
  SkillRankingResponse,
  SkillTrendPoint,
  DiscordBinding,
  DiscordChannelInfo,
  CronJobGlobal,
  MachineStatus,
  HeatmapData,
  AgentStreak,
  Achievement,
  GitHubIssue,
  GitHubIssuesResponse,
  GitHubRepoOption,
  GitHubReposResponse,
  KanbanRepoSource,
  KanbanReview,
  CardAuditLogEntry,
  GitHubComment,
  ChatMessage,
  CachedApiSnapshot,
  DispatchDeliveryEvent,
  DispatchDeliveryEventsResponse,
  AgentSetupRequest,
  AgentSetupResponse,
  ArchiveAgentRequest,
  ArchiveAgentResponse,
  DuplicateAgentRequest,
  RuntimeConfigResponse,
  EscalationMode,
  EscalationSettings,
  EscalationSettingsResponse,
  HealthResponse,
  HealthProviderStatus,
  HealthDispatchOutboxStats,
  PromptManifestRetentionStatus,
  TokenAnalyticsResponse,
  TimelineEvent,
  PipelineConfigResponse,
  PhaseGateInfo,
  VoiceConfigPutBody,
  VoiceConfigResponse,
  // #2050 P3 finding 16 — type companions to getHomeKpiTrends.
  HomeKpiTrendsResponse,
  HomeKpiSeries,
  HomeKpiRateLimit,
  HomeKpiRateLimitProvider,
} from "./client";

// ── Error type guard ──
// #2050 P2 finding 9 — defer to the real ApiRequestError class. The previous
// guard tested for a `code` field the thrown Error never had, so it was dead
// code. Now treats `instanceof ApiRequestError` *or* any error-like with a
// `string` code as a match (the latter for HMR-boundary safety).
import { ApiRequestError as ApiRequestErrorClass } from "./client";

export function isApiRequestError(e: unknown): e is ApiRequestErrorClass {
  if (e instanceof ApiRequestErrorClass) return true;
  return (
    typeof e === "object" &&
    e !== null &&
    "code" in e &&
    typeof (e as { code: unknown }).code === "string"
  );
}
